//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.29 at 04:39:42 AM IRST 
//


package com.hotelapp.xml.mail;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="payablePrice" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="discountPrice" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="roomName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "payablePrice",
    "discountPrice",
    "roomName",
    "email"
})
@XmlRootElement(name = "sendEmailRequest")
public class SendEmailRequest {

    protected int payablePrice;
    protected int discountPrice;
    @XmlElement(required = true)
    protected String roomName;
    @XmlElement(required = true)
    protected String email;

    /**
     * Gets the value of the payablePrice property.
     * 
     */
    public int getPayablePrice() {
        return payablePrice;
    }

    /**
     * Sets the value of the payablePrice property.
     * 
     */
    public void setPayablePrice(int value) {
        this.payablePrice = value;
    }

    /**
     * Gets the value of the discountPrice property.
     * 
     */
    public int getDiscountPrice() {
        return discountPrice;
    }

    /**
     * Sets the value of the discountPrice property.
     * 
     */
    public void setDiscountPrice(int value) {
        this.discountPrice = value;
    }

    /**
     * Gets the value of the roomName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRoomName() {
        return roomName;
    }

    /**
     * Sets the value of the roomName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRoomName(String value) {
        this.roomName = value;
    }

    /**
     * Gets the value of the email property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the value of the email property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmail(String value) {
        this.email = value;
    }

}
